name = "Constructs"
uuid = "ba9efadc-3ee3-4b4a-abe2-d0e326fbcffa"
authors = ["Yong-an Lu <miroox@outlook.com>"]
version = "0.1.0"

[deps]
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Intervals = "1"
julia = "1.6"
