name = "Construct"
uuid = "ba9efadc-3ee3-4b4a-abe2-d0e326fbcffa"
authors = ["Yong-an Lu <miroox@outlook.com>"]
version = "0.1.0"

[deps]
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
Intervals = "1"
MacroTools = "^0.5"
julia = "1.6"
